export default {
  "01d6eddc": [() => import(/* webpackChunkName: "01d6eddc" */ "@site/i18n/ko/docusaurus-plugin-content-docs/current/index.md"), "@site/i18n/ko/docusaurus-plugin-content-docs/current/index.md", require.resolveWeak("@site/i18n/ko/docusaurus-plugin-content-docs/current/index.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "20ef1d1a": [() => import(/* webpackChunkName: "20ef1d1a" */ "@site/i18n/ko/docusaurus-plugin-content-docs/current/architecture/ioc-container.md"), "@site/i18n/ko/docusaurus-plugin-content-docs/current/architecture/ioc-container.md", require.resolveWeak("@site/i18n/ko/docusaurus-plugin-content-docs/current/architecture/ioc-container.md")],
  "38368674": [() => import(/* webpackChunkName: "38368674" */ "@site/docs/overview/configuration.md"), "@site/docs/overview/configuration.md", require.resolveWeak("@site/docs/overview/configuration.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "753cb6b2": [() => import(/* webpackChunkName: "753cb6b2" */ "@site/docs/overview/intro.md"), "@site/docs/overview/intro.md", require.resolveWeak("@site/docs/overview/intro.md")],
  "83c94f95": [() => import(/* webpackChunkName: "83c94f95" */ "@site/i18n/ko/docusaurus-plugin-content-docs/current/overview/quickstart.md"), "@site/i18n/ko/docusaurus-plugin-content-docs/current/overview/quickstart.md", require.resolveWeak("@site/i18n/ko/docusaurus-plugin-content-docs/current/overview/quickstart.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c9dd6e46": [() => import(/* webpackChunkName: "c9dd6e46" */ "@generated/docusaurus-plugin-content-docs/default/p/sprout-ko-0f4.json"), "@generated/docusaurus-plugin-content-docs/default/p/sprout-ko-0f4.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/sprout-ko-0f4.json")],
  "d7d92410": [() => import(/* webpackChunkName: "d7d92410" */ "@site/docs/overview/roadmap.md"), "@site/docs/overview/roadmap.md", require.resolveWeak("@site/docs/overview/roadmap.md")],};
